CREATE TABLE DEPARTMENT_DESIGNATION (
	ID SERIAL PRIMARY KEY,
  	NAME VARCHAR(64) NOT NULL,
    EXPECTED_TARGET INTEGER NOT NULL DEFAULT 0,
  	CONSTRAINT dprtmnt_target_chk CHECK ( EXPECTED_TARGET >= 0 )
);

CREATE TABLE MEDIA_CATEGORY (
	ID SERIAL PRIMARY KEY,
  	NAME VARCHAR(32) NOT NULL,
  	TYPE VARCHAR(16) NOT NULL,
  	YEARLY_QUOTA INTEGER NOT NULL,
  	CONSTRAINT category_quota_chk CHECK (YEARLY_QUOTA > 0),
  	CONSTRAINT med_type CHECK (TYPE IN ('AUDIO', 'VIDEO', 'TEXT', 'OTHER'))
);

CREATE TABLE POSITION (
	ID SERIAL PRIMARY KEY,
  	NAME VARCHAR(32) NOT NULL,
  	SALARY INTEGER NOT NULL DEFAULT 0,
 	ACCESS_LEVEL INTEGER NOT NULL DEFAULT 1,
  	CONSTRAINT position_attributes_chk CHECK (SALARY >= 0 AND ACCESS_LEVEL >= 1 AND ACCESS_LEVEL <= 4)
);

CREATE TABLE PUBLISHER (
  	ID SERIAL PRIMARY KEY,
  	NAME VARCHAR(32) NOT NULL DEFAULT 'Undesignated org',
  	FOUNDATION_DATE TIMESTAMP,
  	EMPLOYEES_COUNT INTEGER NOT NULL DEFAULT 1,
  	REGISTRATION_CODE VARCHAR(64) NOT NULL DEFAULT 'Awaiting police data',
  	REPRESENTATIVE VARCHAR(64) NOT NULL DEFAULT 'Awaiting police data'
  	CONSTRAINT employee_count_chk CHECK (EMPLOYEES_COUNT >= 0)
);

CREATE TABLE MEDIA_PRODUCT (
	ID SERIAL PRIMARY KEY,
  	TITLE VARCHAR(64) NOT NULL DEFAULT 'Unknown',
  	ESTIMATION INTEGER,
  	STATUS VARCHAR(32) NOT NULL,
  	MEDIA_CATEGORY_ID INTEGER REFERENCES MEDIA_CATEGORY (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  	PUBLISHER_ID INTEGER REFERENCES PUBLISHER (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  	CONSTRAINT med_status CHECK (STATUS IN ('Discovered', 'Processing', 'Redacted', 'Rereleased', 'Destroyed'))
);

CREATE TABLE DEPARTMENT (
	ID SERIAL PRIMARY KEY,
  	NAME VARCHAR(64),
  	STATUS VARCHAR(16) NOT NULL DEFAULT 'Suspended',
  	DATE_FOUNDATION TIMESTAMP,
  	DATE_TERMINATION TIMESTAMP,
  	DESIGNATION_ID INTEGER REFERENCES DEPARTMENT_DESIGNATION ON DELETE CASCADE ON UPDATE CASCADE,
  	MEDIA_CATEGORY_ID INTEGER REFERENCES MEDIA_CATEGORY ON DELETE CASCADE ON UPDATE CASCADE,
  	CONSTRAINT dep_status CHECK (STATUS IN ('Active', 'Suspended', 'Terminated'))
);

CREATE TABLE EMPLOYEE (
	ID SERIAL PRIMARY KEY,
  	NAME VARCHAR(32) NOT NULL,
  	AGE INTEGER,
  	ADDRESS VARCHAR(256),
  	MARRIED BOOLEAN,
  	CHILDREN_AMOUNT INTEGER,
  	NOTES VARCHAR(256),
  	DEPARTMENT_ID INTEGER REFERENCES DEPARTMENT (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  	POSITION_ID INTEGER REFERENCES POSITION (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE GUIDELINE (
	ID SERIAL PRIMARY KEY,
  	NAME VARCHAR(64) NOT NULL DEFAULT 'Untitled Dep. Guideline',
  	RELEASE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
  	NEWSPEAK_VERSION INTEGER,
  	DEPARTMENT_ID INTEGER REFERENCES DEPARTMENT (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  	AUTHOR_ID INTEGER REFERENCES EMPLOYEE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  	CONSTRAINT guideline_chk CHECK ( NEWSPEAK_VERSION IN (1, 2) )
);

CREATE TABLE RULE (
	ID SERIAL PRIMARY KEY,
  	DESCRIPTION VARCHAR(256) NOT NULL,
  	INSTALLMENT_DATE TIMESTAMP,
  	PUNISHMENT VARCHAR(32),
  	GUIDELINE_ID INTEGER REFERENCES GUIDELINE (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DEVICE (
	ID SERIAL PRIMARY KEY,
  	TYPE VARCHAR(32) NOT NULL DEFAULT 'OTHER',
  	MODEL VARCHAR(256),
  	DATE_MADE TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
  	DATE_TERMINATED TIMESTAMP,
  	MAINTAINER_ID INTEGER REFERENCES EMPLOYEE (ID) ON UPDATE CASCADE ON DELETE CASCADE,
  	CONSTRAINT dev_type CHECK (TYPE IN ('VIDEO_CAPTURE', 'AUDIO_CAPTURE', 'TEXT_CAPTURE', 'OTHER'))
);

CREATE TABLE MINISTRY_CASE (
	ID SERIAL PRIMARY KEY,
  	STATE VARCHAR(32) NOT NULL DEFAULT 'Submitted',
  	ASSIGNEE_ID INTEGER REFERENCES EMPLOYEE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  	CONSTRAINT case_state CHECK (STATE IN ('Incomplete', 'Submitted',
  	'Open',
  	'In Progress',
  	'Invalid',
  	'Closed',
  	'Reopened',
  	'Frozen'))
);

CREATE TABLE CASE_MEDIA_RELATION (
	CASE_ID INTEGER REFERENCES MINISTRY_CASE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  	MEDIA_ID INTEGER REFERENCES MEDIA_PRODUCT (ID) ON DELETE SET NULL ON UPDATE CASCADE,
  	PRIMARY KEY (CASE_ID, MEDIA_ID)
);

CREATE TABLE CASE_DEVICE_RELATION (
	CASE_ID INTEGER REFERENCES MINISTRY_CASE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  	DEVICE_ID INTEGER REFERENCES DEVICE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  	PRIMARY KEY (CASE_ID, DEVICE_ID)
);
